from pet_cats import pet_cats
class goods_creator:
    def input_goods():
        goods_array=[]
        print("Type of goods: 1 - Cats, 2- Rodents, 3 - Cage, 4 - Feeders, 5 - Stern, 6 - Toys")
        new_goods=int(input("Please input type goods: "))
        id_goods=input("Please input id goods: ")
        if new_goods==1:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            kind_pet=input("Please input kind of pet: ")
            age=input("Please input age pet: ")
            cats_breed=input("Please input cats breed: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(kind_pet)
            goods_array.append(age)
            goods_array.append(cats_breed)
        elif new_goods==2:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            kind_pet=input("Please input kind of pet: ")
            age=input("Please input age pet: ")
            rodent_breed=input("Please input rodent breed: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(kind_pet)
            goods_array.append(age)
            goods_array.append(rodent_breed)
        elif new_goods==3:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            cage_for_kind_animal=input("Please input cage for kind animal: ")
            size=input("Please input size: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(cage_for_kind_animal)
            goods_array.append(size)
        elif new_goods==4:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            kind_item=input("Please input kind item: ")
            expiration_date=input("Please input expiration date: ")
            feeder_for_kind_animal=input("Please input feeder for kind animal: ")
            feeder_size=input("Please input feeder size: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(kind_item)
            goods_array.append(expiration_date)
            goods_array.append(feeder_for_kind_animal)
            goods_array.append(feeder_size)
        elif new_goods==5:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            stern_for_kind_animal=input("Please input stern for kind animal: ")
            weight=input("Please input weight: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(stern_for_kind_animal)
            goods_array.append(weight)
        elif new_goods==6:
            name=input("Please input name goods: ")
            price=int(input("Please input price goods: "))
            kind_item=input("Please input kind item: ")
            expiration_date=input("Please input expiration date: ")
            toy_for_kind_animal=input("Please input toy for kind animal: ")
            kind_of_toy=input("Please input kind of toy: ")
            goods_array.append(name)
            goods_array.append(price)
            goods_array.append(kind_item)
            goods_array.append(expiration_date)
            goods_array.append(toy_for_kind_animal)
            goods_array.append(kind_of_toy)
        else:
            pass
        print(id_goods,goods_array)
            
